[2025-10-29 03:27:36] Persistent Runner started for gpt2
[2025-10-29 03:27:36] Loading model on CPU...
[2025-10-29 03:27:38] Model loaded successfully.
[2025-10-29 03:27:38] âš¡ Running initial prompt: pope...
[2025-10-29 03:27:38] [ERROR] During initial inference: The following `model_kwargs` are not used by the model: ['cache_dir'] (note: typos in the generate arguments will also show up in this list)
[2025-10-29 03:27:38] Waiting for new prompts (via stdin)...
[2025-10-29 03:27:44]  Signal received. Shutting down gracefully...
[2025-10-29 03:27:44] Persistent runner terminated.
